/** @type {import('stylelint').Config} */
export default {
  extends: ["stylelint-config-standard-scss"],
  plugins: ["stylelint-scss", "stylelint-order"],
  rules: {
    "at-rule-no-vendor-prefix": true,
    "block-no-empty": true,
    "color-hex-length": "short",
    "color-no-invalid-hex": true,
    "comment-no-empty": true,
    "comment-whitespace-inside": "always",
    "custom-property-no-missing-var-function": true,
    "declaration-block-no-duplicate-custom-properties": true,
    "declaration-block-no-duplicate-properties": true,
    "declaration-block-no-redundant-longhand-properties": true,
    "declaration-block-no-shorthand-property-overrides": true,
    "declaration-block-single-line-max-declarations": 0,
    "font-family-no-duplicate-names": true,
    "font-weight-notation": "numeric",
    "function-calc-no-unspaced-operator": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-no-unknown": true,
    "function-url-no-scheme-relative": true,
    "function-url-quotes": ["always", { except: "empty" }],
    "length-zero-no-unit": true,
    "media-feature-name-no-unknown": true,
    "media-feature-name-no-vendor-prefix": true,
    "named-grid-areas-no-invalid": true,
    "no-duplicate-at-import-rules": true,
    "no-invalid-double-slash-comments": true,
    "no-invalid-position-at-import-rule": [
      true,
      { ignoreAtRules: ["use", "forward"] },
    ],
    "no-irregular-whitespace": true,
    "no-unknown-animations": true,
    "order/properties-alphabetical-order": true,
    "property-no-unknown": true,
    "property-no-vendor-prefix": true,
    "selector-no-vendor-prefix": true,
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-element-no-unknown": [
      true,
      { ignorePseudoElements: ["ng-deep"] },
    ],
    "selector-type-case": "lower",
    "shorthand-property-no-redundant-values": true,
    "string-no-newline": true,
    "unit-allowed-list": ["px", "em", "rem", "%", "fr", "s", "vh", "vw", "deg"],
    "unit-no-unknown": true,
  },
};
